import { useStore } from "@/store";

// Base URL for the FastAPI backend service
const API_URL =
  (typeof process !== "undefined" ? process.env?.VITE_API_URL : null) ||
  import.meta.env.VITE_API_URL ||
  "http://127.0.0.1:8001";

/**
 * Streams the RAG chat response word-by-word (token-by-token) from the backend.
 * Uses the browser's native Fetch API and ReadableStream to consume Server-Sent Events (SSE).
 *
 * @param message The user query text.
 * @param ocean Selected ocean filter.
 * @param history Array of previous chat message history turns.
 * @param signal AbortSignal from an AbortController to allow stopping generation midway.
 * @param onMeta Callback triggered when the initial metadata packet (SQL, chart type, database data) is received. Returns the unique message ID.
 * @param onChunk Callback triggered when a new text word/token is streamed from the LLM.
 * @param onError Callback triggered if a connection or streaming error occurs.
 * @param onDone Callback triggered when the stream finishes successfully or cleanups are needed.
 */
export async function streamChat(
  message: string,
  ocean: string,
  history: Array<{ role: string; text: string }>,
  signal: AbortSignal,
  onMeta: (meta: any) => string,
  onChunk: (messageId: string, text: string) => void,
  onError: (messageId: string, errorText: string) => void,
  onDone: () => void
) {
  let messageId = ""; // Track the unique message ID assigned to the AI response bubble
  
  try {
    // Call the streaming route with HTTP POST and pass the abort controller signal
    const response = await fetch(`${API_URL}/api/chat/stream`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ message, ocean, history }),
      signal,
    });

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    // Get the stream reader to read incoming byte streams incrementally
    const reader = response.body?.getReader();
    if (!reader) {
      throw new Error("No response body reader available.");
    }

    const decoder = new TextDecoder();
    let buffer = ""; // Holds incoming fragments of text until they form a complete SSE line

    while (true) {
      const { value, done } = await reader.read();
      if (done) break;

      // Decode the binary chunk to string and append it to our buffer
      buffer += decoder.decode(value, { stream: true });
      
      // SSE lines are separated by newlines (\n)
      const lines = buffer.split("\n");
      
      // Keep the last element in the buffer because it might be an incomplete line
      // received halfway through packet transmission. It will be parsed in the next iteration.
      buffer = lines.pop() || "";

      for (const line of lines) {
        const trimmed = line.trim();
        // Server-Sent Events prefix lines with "data: "
        if (!trimmed.startsWith("data: ")) continue;

        const dataStr = trimmed.slice(6).trim();
        if (!dataStr) continue;

        try {
          // Parse the JSON payload sent by the backend
          const event = JSON.parse(dataStr);
          
          if (event.type === "meta") {
            // METADATA packet: Contains SQL query used, Plotly chart type, and database rows.
            // Triggered at the very start of the stream so the UI can render charts immediately.
            messageId = onMeta({
              answer: "",
              chart_type: event.chart_type,
              sql_used: event.sql_used,
              data: event.data || [],
              float_ids: event.float_ids || [],
            });
          } else if (event.type === "chunk") {
            // TEXT CHUNK: A word or set of characters generated by the LLM.
            if (messageId) {
              onChunk(messageId, event.text);
            }
          } else if (event.type === "error") {
            // ERROR packet: Sent if LLM generation fails midway.
            if (messageId) {
              onError(messageId, event.text);
            }
          } else if (event.type === "done") {
            // COMPLETE packet: Sent when LLM finishes generation successfully.
            onDone();
            return;
          }
        } catch (e) {
          console.error("Error parsing SSE line:", line, e);
        }
      }
    }
  } catch (err: any) {
    // Handle the user clicking the "Stop" button (which aborts the network request)
    if (err.name === "AbortError") {
      console.log("Stream aborted by user");
      return;
    }
    
    console.error("Stream reader error:", err);
    
    if (messageId) {
      // Append connection failure warning to the existing bubble
      onError(messageId, `\n\n[Connection Error: ${err.message}]`);
    } else {
      // If the connection failed before the metadata packet was received, create a fallback bubble
      const errorMsg = `The server failed to respond. Please try again. (Error: ${err.message})`;
      onMeta({
        answer: errorMsg,
        chart_type: "none",
        sql_used: "-- Connection failed",
        data: [],
        float_ids: [],
      });
    }
    onDone();
  }
}
